service: megabytes-auth
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1
  environment:
    USER_POOL_ID: { Ref: UserPool }
    CLIENT_ID: {Ref: UserClient }
    STAGE: ${env:STAGE}
    REGION: ${env:REGION}
    ACCOUNT_NAME: ${env:ACCOUNT_NAME}
    STACK_FAMILY: ${env:STACK_FAMILY}
    ACCOUNT_ID: ${env:ACCOUNT_ID}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
      Resource: "*"
  
functions:
  login:
    handler: infrastructure/functions/account/login/main.handler
    events:
      - http:
          path: /login
          method: post
          cors: true
    package:
      include:
        - infrastructure/functions/account/login/**
        - infrastructure/shared_code/**
  profile:
    handler: infrastructure/functions/account/profile/main.handler
    events:
      - http:
          path: /profile
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ecswr4
    package:
      include:
        - infrastructure/functions/account/profile/**
        - infrastructure/shared_code/**
  signup:
    handler: infrastructure/functions/account/signup/main.handler
    timeout: 30
    events:
      - http:
          path: /signup
          method: post
    package:
      include:
        - infrastructure/functions/account/signup/**
        - infrastructure/shared_code/**
  verifySignup:
    handler: infrastructure/functions/account/verify_signup/main.handler
    timeout: 30
    events:
      - http:
          path: /verify
          method: post
    package:
      include:
        - infrastructure/functions/account/verify_signup/**
        - infrastructure/shared_code/**
  resendVerification:
    handler: infrastructure/functions/account/resend_verification/main.handler
    timeout: 30
    events:
      - http:
          path: /resend
          method: post
    package:
      include:
        - infrastructure/functions/account/resend_verification/**
        - infrastructure/shared_code/**

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: megabytes-auth-pool
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 8
        AutoVerifiedAttributes: ["email"]
    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: user-pool-ui
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"
